# Generated by Django 5.2.7 on 2026-02-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0002_alter_paperentry_options_alter_client_phone_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paperentry",
            options={},
        ),
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=models.CharField(max_length=50),
        ),
    ]
