# Generated by Django 5.2.7 on 2026-02-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0003_alter_paperentry_options_alter_company_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
