# Generated by Django 5.2.7 on 2026-02-17 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0004_alter_company_address_alter_company_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paperentry",
            name="kind",
            field=models.CharField(
                choices=[("REAL", "Real"), ("SUPPORT", "Supporting")],
                default="REAL",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="paperentry",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"kind": "REAL"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supporting_papers",
                to="papers.paperentry",
            ),
        ),
    ]
