# Generated by Django 5.2.7 on 2026-07-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_paperentry_kind_paperentry_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperentry',
            name='kind',
            field=models.CharField(choices=[('REAL', 'Real'), ('SUPPORT', 'Supporting'), ('PO', 'Purchase Order')], default='REAL', max_length=10),
        ),
    ]
