# Generated by Django 5.2.7 on 2026-07-30 05:51

import django.db.models.deletion
from django.db import migrations, models


BANK_ACCOUNTS = {
    "solid_connections": [
        {
            "label": "Stanbic Bank - Lusaka Main",
            "bank_name": "Stanbic Bank Zambia",
            "account_name": "Solid Connections Zambia Limited",
            "account_number": "9130001606976",
            "branch": "Lusaka Main",
            "branch_code": "040002",
            "swift_code": "SBICZMLX",
            "is_default": True,
        },
        {
            "label": "Indo Zambia Bank - Lusaka Main",
            "bank_name": "Indo Zambia Bank",
            "account_name": "Solid Connections Zambia Ltd",
            "account_number": "0012030002718",
            "branch": "Lusaka Main Branch",
            "sort_code": "090001",
            "swift_code": "INZAZMLX",
            "is_default": False,
        },
    ],
    "solid-connections-z-ltd": [
        {
            "label": "Stanbic Bank - Lusaka Main",
            "bank_name": "Stanbic Bank Zambia",
            "account_name": "Solid Connections Zambia Limited",
            "account_number": "9130001606976",
            "branch": "Lusaka Main",
            "branch_code": "040002",
            "swift_code": "SBICZMLX",
            "is_default": True,
        },
        {
            "label": "Indo Zambia Bank - Lusaka Main",
            "bank_name": "Indo Zambia Bank",
            "account_name": "Solid Connections Zambia Ltd",
            "account_number": "0012030002718",
            "branch": "Lusaka Main Branch",
            "sort_code": "090001",
            "swift_code": "INZAZMLX",
            "is_default": False,
        },
    ],
    "universal_general": [
        {
            "label": "Indo Zambia Bank - ZMW/USD",
            "bank_name": "Indo Zambia Bank",
            "account_name": "Universal General Supplies Ltd",
            "account_number": "0012030002719",
            "account_number_usd": "0012031001081",
            "branch": "Lusaka Main Branch",
            "sort_code": "090001",
            "swift_code": "INZAZMLX",
            "is_default": True,
        },
        {
            "label": "Stanbic Bank - Manda Hill",
            "bank_name": "Stanbic Bank Zambia",
            "account_name": "Universal General Supplies Limited",
            "account_number": "9130004986877",
            "branch": "Manda Hill",
            "branch_code": "040015",
            "swift_code": "SBICZMLX",
            "is_default": False,
        },
    ],
    "raised_right": [
        {
            "label": "Zanaco - Monze",
            "bank_name": "Zanaco",
            "account_name": "Raised Right Investments Limited",
            "account_number": "5848113500195",
            "branch": "Monze",
            "branch_code": "056",
            "sort_code": "01-37-57",
            "swift_code": "ZNCOZMLU",
            "is_default": True,
        },
        {
            "label": "First Capital Bank - Kamwala",
            "bank_name": "First Capital Bank",
            "account_name": "Raised Right Investments Limited",
            "account_number": "0006203001372",
            "branch": "Kamwala",
            "branch_code": "28006",
            "swift_code": "FRCGZMLU",
            "is_default": False,
        },
    ],
}


def seed_bank_accounts(apps, schema_editor):
    Company = apps.get_model("papers", "Company")
    CompanyBankAccount = apps.get_model("papers", "CompanyBankAccount")

    for slug, accounts in BANK_ACCOUNTS.items():
        try:
            company = Company.objects.get(slug=slug)
        except Company.DoesNotExist:
            continue

        for account in accounts:
            CompanyBankAccount.objects.update_or_create(
                company=company,
                bank_name=account["bank_name"],
                account_number=account.get("account_number", ""),
                defaults=account,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_alter_paperentry_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('bank_name', models.CharField(max_length=120)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=80)),
                ('account_number_usd', models.CharField(blank=True, max_length=80, verbose_name='USD account number')),
                ('branch', models.CharField(blank=True, max_length=120)),
                ('branch_code', models.CharField(blank=True, max_length=80)),
                ('sort_code', models.CharField(blank=True, max_length=80)),
                ('swift_code', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='papers.company')),
            ],
            options={
                'ordering': ['company__name', '-is_default', 'bank_name', 'label'],
            },
        ),
        migrations.AddField(
            model_name='paperentry',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_entries', to='papers.companybankaccount'),
        ),
        migrations.RunPython(seed_bank_accounts, migrations.RunPython.noop),
    ]
