# Generated by Django 5.2.7 on 2025-12-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=200)),
                ("customer", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("project_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WON", "Won"),
                            ("LOST", "Lost"),
                            ("PENDING", "Pending"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
