# Generated by Django 5.2.7 on 2025-12-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projections", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectrecord",
            options={"ordering": ["-project_date"]},
        ),
        migrations.AddField(
            model_name="projectrecord",
            name="year",
            field=models.PositiveIntegerField(default=2025, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="projectrecord",
            name="company",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="projectrecord",
            name="customer",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="projectrecord",
            name="project_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="projectrecord",
            name="status",
            field=models.CharField(
                choices=[("WON", "Won"), ("LOST", "Lost"), ("PENDING", "Pending")],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
