# Generated by Django 5.2.7 on 2025-12-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projections", "0002_alter_projectrecord_options_projectrecord_year_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectrecord",
            options={
                "ordering": ["-project_date"],
                "verbose_name": "Project Record",
                "verbose_name_plural": "Project Records",
            },
        ),
        migrations.AddField(
            model_name="projectrecord",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="projectrecord",
            name="year",
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
