# Generated by Django 5.2.7 on 2025-12-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projections",
            "0003_alter_projectrecord_options_projectrecord_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectrecord",
            options={"ordering": ["-project_date"]},
        ),
        migrations.AddField(
            model_name="projectrecord",
            name="description",
            field=models.TextField(
                blank=True, help_text="Detailed project description"
            ),
        ),
        migrations.AddField(
            model_name="projectrecord",
            name="title",
            field=models.CharField(
                db_index=True,
                default="Untitled Project",
                help_text="Short project title",
                max_length=255,
            ),
        ),
    ]
