# Generated by Django 5.2.7 on 2026-01-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projections", "0004_alter_projectrecord_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectrecord",
            name="completion_status",
            field=models.CharField(
                choices=[
                    ("PENDING_EVALUATION", "Pending Evaluation"),
                    ("NOT_COMPLETED", "Not Completed"),
                    ("COMPLETED", "Completed"),
                ],
                db_index=True,
                default="PENDING_EVALUATION",
                help_text="Project execution and evaluation status",
                max_length=25,
            ),
        ),
    ]
