# Generated by Django 5.2.7 on 2026-01-19 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projections", "0005_projectrecord_completion_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectrecord",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total contract/project value",
                max_digits=14,
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount received for this payment",
                        max_digits=14,
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(help_text="Date payment was received"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Receipt number, bank reference, or transaction ID",
                        max_length=100,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes about the payment"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="projections.projectrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date"],
            },
        ),
    ]
