# Generated by Django 5.2.7 on 2026-07-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projections", "0006_alter_projectrecord_amount_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectrecord",
            name="is_internal",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Only visible on internal dashboard",
            ),
        ),
    ]
