# Generated by Django 5.2.7 on 2026-05-23 04:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expensetag",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="projectexpense",
            options={"ordering": ["-date", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="projectrecord",
            options={"ordering": ["start_date", "created_at"]},
        ),
        migrations.AddField(
            model_name="projectexpense",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name="projectrecord",
            constraint=models.UniqueConstraint(
                fields=("company", "project_supply", "client"),
                name="unique_company_project_client",
            ),
        ),
    ]
