# Generated by Django 5.2.7 on 2026-05-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_alter_expensetag_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectrecord",
            name="tax_type",
            field=models.CharField(
                choices=[("NONE", "No Tax"), ("TOT", "5% TOT"), ("VAT", "16% VAT")],
                default="NONE",
                max_length=10,
            ),
        ),
    ]
