# Generated by Django 5.2.7 on 2026-05-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_projectrecord_tax_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingProjectRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255)),
                (
                    "project_supply",
                    models.CharField(max_length=255, verbose_name="Project / Supply"),
                ),
                ("client", models.CharField(max_length=255)),
                ("submission_date", models.DateField(blank=True, null=True)),
                ("expected_award_date", models.DateField(blank=True, null=True)),
                (
                    "contract_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("NONE", "No Tax"),
                            ("TOT", "5% TOT"),
                            ("VAT", "16% VAT"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Submitted", "Submitted"),
                            ("Awaiting Award", "Awaiting Award"),
                            ("Not Awarded", "Not Awarded"),
                            ("Awarded", "Awarded"),
                        ],
                        default="Submitted",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["submission_date", "created_at"],
            },
        ),
    ]
