# Generated by Django 5.2.7 on 2026-07-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_pendingprojectrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectrecord",
            name="is_internal",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
