# Generated by Django 5.2.7 on 2026-07-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_projectrecord_is_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingprojectrecord',
            name='currency',
            field=models.CharField(choices=[('ZMW', 'ZMW'), ('USD', 'USD')], default='ZMW', max_length=3),
        ),
        migrations.AddField(
            model_name='pendingprojectrecord',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Use the ZMW value for 1 USD. Leave as 1 for ZMW projects.', max_digits=12, verbose_name='Exchange rate to ZMW'),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='currency',
            field=models.CharField(choices=[('ZMW', 'ZMW'), ('USD', 'USD')], default='ZMW', max_length=3),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Use the ZMW value for 1 USD. Leave as 1 for ZMW expenses.', max_digits=12, verbose_name='Exchange rate to ZMW'),
        ),
        migrations.AddField(
            model_name='projectrecord',
            name='currency',
            field=models.CharField(choices=[('ZMW', 'ZMW'), ('USD', 'USD')], default='ZMW', max_length=3),
        ),
        migrations.AddField(
            model_name='projectrecord',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Use the ZMW value for 1 USD. Leave as 1 for ZMW projects.', max_digits=12, verbose_name='Exchange rate to ZMW'),
        ),
    ]
