# Generated by Django 5.2.7 on 2026-07-17 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_pendingprojectrecord_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('ZMW', 'ZMW'), ('USD', 'USD')], default='ZMW', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, help_text='Use the ZMW value for 1 USD. Leave as 1 for ZMW payments.', max_digits=12, verbose_name='Exchange rate to ZMW')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='reports.projectrecord')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
