# Generated by Django 5.2.7 on 2026-07-19 09:09

from django.db import migrations, models


def project_tax_rate(tax_type):
    if tax_type == "TOT":
        return "0.05"

    if tax_type == "VAT":
        return "0.16"

    return "0.00"


def copy_project_tax_rate_to_payments(apps, schema_editor):
    ProjectPayment = apps.get_model("reports", "ProjectPayment")

    for payment in ProjectPayment.objects.select_related("project"):
        payment.tax_rate = project_tax_rate(payment.project.tax_type)
        payment.save(update_fields=["tax_rate"])


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_projectpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpayment',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.RunPython(
            copy_project_tax_rate_to_payments,
            migrations.RunPython.noop,
        ),
    ]
