# Generated by Django 5.2.7 on 2025-11-20 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="tender",
            options={"ordering": ["-start_date"]},
        ),
    ]
